[project]
name = "geopython-form"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.20.0",
    "geopandas>=1.1.1",
    "geopy>=2.4.1",
    "ipykernel>=6.30.0",
    "matplotlib>=3.10.5",
]
